export interface TickerEntry {
  ticker: string;
  name: string;
  sector: string;
  industry: string;
  assetType: "equity" | "etf";
  exchange: string;
}

export const EXPANDED_TICKERS: TickerEntry[] = [
  // ─── TECHNOLOGY ───────────────────────────────────────────────────────
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "GOOGL", name: "Alphabet Inc.", sector: "Technology", industry: "Internet Content & Information", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Technology", industry: "Social Media", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AMD", name: "Advanced Micro Devices Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "INTC", name: "Intel Corporation", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NYSE" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", sector: "Technology", industry: "Computer Networking", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "TXN", name: "Texas Instruments Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AMAT", name: "Applied Materials Inc.", sector: "Technology", industry: "Semiconductor Equipment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MU", name: "Micron Technology Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "LRCX", name: "Lam Research Corporation", sector: "Technology", industry: "Semiconductor Equipment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology", industry: "Semiconductor Equipment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CDNS", name: "Cadence Design Systems Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PANW", name: "Palo Alto Networks Inc.", sector: "Technology", industry: "Cybersecurity", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology", industry: "Cybersecurity", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc.", sector: "Technology", industry: "Cybersecurity", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology", industry: "Cybersecurity", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Technology", industry: "Cloud Computing", assetType: "equity", exchange: "NYSE" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MDB", name: "MongoDB Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology", industry: "Cloud Computing", assetType: "equity", exchange: "NYSE" },
  { ticker: "PLTR", name: "Palantir Technologies Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "SMCI", name: "Super Micro Computer Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ARM", name: "Arm Holdings plc", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ADSK", name: "Autodesk Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WDAY", name: "Workday Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "VEEV", name: "Veeva Systems Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "MSTR", name: "MicroStrategy Incorporated", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HUBS", name: "HubSpot Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "TTD", name: "The Trade Desk Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "APP", name: "AppLovin Corporation", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "DELL", name: "Dell Technologies Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NYSE" },
  { ticker: "HPQ", name: "HP Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NYSE" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NYSE" },
  { ticker: "IBM", name: "IBM Corporation", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "ACN", name: "Accenture plc", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "INFY", name: "Infosys Limited", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "WIT", name: "Wipro Limited", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "ANET", name: "Arista Networks Inc.", sector: "Technology", industry: "Computer Networking", assetType: "equity", exchange: "NYSE" },
  { ticker: "CIEN", name: "Ciena Corporation", sector: "Technology", industry: "Computer Networking", assetType: "equity", exchange: "NYSE" },
  { ticker: "ON", name: "ON Semiconductor Corporation", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MRVL", name: "Marvell Technology Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "NXPI", name: "NXP Semiconductors N.V.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ADI", name: "Analog Devices Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MCHP", name: "Microchip Technology Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "QRVO", name: "Qorvo Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WOLF", name: "Wolfspeed Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NYSE" },
  { ticker: "KEYS", name: "Keysight Technologies Inc.", sector: "Technology", industry: "Scientific & Technical Instruments", assetType: "equity", exchange: "NYSE" },
  { ticker: "PTC", name: "PTC Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "TYL", name: "Tyler Technologies Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "VRSN", name: "Verisign Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ZBRA", name: "Zebra Technologies Corporation", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FIVN", name: "Five9 Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PCTY", name: "Paylocity Holding Corporation", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "EPAM", name: "EPAM Systems Inc.", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "GFS", name: "GlobalFoundries Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CRDO", name: "Credo Technology Group Holding Ltd", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SMAR", name: "Smartsheet Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "CFLT", name: "Confluent Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "IOT", name: "Samsara Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "TOST", name: "Toast Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "MNDY", name: "monday.com Ltd.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WIX", name: "Wix.com Ltd.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FVRR", name: "Fiverr International Ltd.", sector: "Technology", industry: "Internet Content & Information", assetType: "equity", exchange: "NYSE" },
  { ticker: "TWLO", name: "Twilio Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "PSTG", name: "Pure Storage Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NYSE" },
  { ticker: "WD", name: "Western Digital Corporation", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ERIC", name: "Telefonaktiebolaget LM Ericsson", sector: "Technology", industry: "Communication Equipment", assetType: "equity", exchange: "NYSE" },
  { ticker: "NOK", name: "Nokia Corporation", sector: "Technology", industry: "Communication Equipment", assetType: "equity", exchange: "NYSE" },
  { ticker: "VNET", name: "21Vianet Group Inc.", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FFIV", name: "F5 Inc.", sector: "Technology", industry: "Computer Networking", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CTSH", name: "Cognizant Technology Solutions", sector: "Technology", industry: "Information Technology Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "OKTA", name: "Okta Inc.", sector: "Technology", industry: "Cybersecurity", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "VRNS", name: "Varonis Systems Inc.", sector: "Technology", industry: "Cybersecurity", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AI", name: "C3.ai Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "PATH", name: "UiPath Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "U", name: "Unity Software Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "ZM", name: "Zoom Video Communications Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ENPH", name: "Enphase Energy Inc.", sector: "Technology", industry: "Semiconductors", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "IONQ", name: "IonQ Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NYSE" },
  { ticker: "RGTI", name: "Rigetti Computing Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ASTS", name: "AST SpaceMobile Inc.", sector: "Technology", industry: "Communication Equipment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BB", name: "BlackBerry Limited", sector: "Technology", industry: "Software - Infrastructure", assetType: "equity", exchange: "NYSE" },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "SQ", name: "Block Inc.", sector: "Technology", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },

  // ─── HEALTHCARE ───────────────────────────────────────────────────────
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "LLY", name: "Eli Lilly and Company", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "BMY", name: "Bristol-Myers Squibb Company", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "CVS", name: "CVS Health Corporation", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HCA", name: "HCA Healthcare Inc.", sector: "Healthcare", industry: "Medical Care Facilities", assetType: "equity", exchange: "NYSE" },
  { ticker: "ELV", name: "Elevance Health Inc.", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "CI", name: "The Cigna Group", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "HUM", name: "Humana Inc.", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "BSX", name: "Boston Scientific Corporation", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "ZTS", name: "Zoetis Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "IQV", name: "IQVIA Holdings Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "A", name: "Agilent Technologies Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "WAT", name: "Waters Corporation", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "MTD", name: "Mettler-Toledo International Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "BAX", name: "Baxter International Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "BIO", name: "Bio-Rad Laboratories Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "TECH", name: "Bio-Techne Corporation", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ALGN", name: "Align Technology Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HOLX", name: "Hologic Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "INCY", name: "Incyte Corporation", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BMRN", name: "BioMarin Pharmaceutical Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "RMD", name: "ResMed Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "DXCM", name: "DexCom Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PODD", name: "Insulet Corporation", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "STE", name: "STERIS plc", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "UHS", name: "Universal Health Services Inc.", sector: "Healthcare", industry: "Medical Care Facilities", assetType: "equity", exchange: "NYSE" },
  { ticker: "CNC", name: "Centene Corporation", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "MOH", name: "Molina Healthcare Inc.", sector: "Healthcare", industry: "Healthcare Plans", assetType: "equity", exchange: "NYSE" },
  { ticker: "IDXX", name: "IDEXX Laboratories Inc.", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "LH", name: "Laboratory Corporation of America Holdings", sector: "Healthcare", industry: "Diagnostics & Research", assetType: "equity", exchange: "NYSE" },
  { ticker: "CAH", name: "Cardinal Health Inc.", sector: "Healthcare", industry: "Medical Distribution", assetType: "equity", exchange: "NYSE" },
  { ticker: "MCK", name: "McKesson Corporation", sector: "Healthcare", industry: "Medical Distribution", assetType: "equity", exchange: "NYSE" },
  { ticker: "HSIC", name: "Henry Schein Inc.", sector: "Healthcare", industry: "Medical Distribution", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WBA", name: "Walgreens Boots Alliance Inc.", sector: "Healthcare", industry: "Medical Distribution", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "XRAY", name: "Dentsply Sirona Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ZBH", name: "Zimmer Biomet Holdings Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "RPRX", name: "Royalty Pharma plc", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HALO", name: "Halozyme Therapeutics Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CRSP", name: "CRISPR Therapeutics AG", sector: "Healthcare", industry: "Biotechnology", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "DOCS", name: "Doximity Inc.", sector: "Healthcare", industry: "Health Information Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "ELAN", name: "Elanco Animal Health Incorporated", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "PRGO", name: "Perrigo Company plc", sector: "Healthcare", industry: "Drug Manufacturers - Specialty & Generic", assetType: "equity", exchange: "NYSE" },
  { ticker: "TFX", name: "Teleflex Incorporated", sector: "Healthcare", industry: "Medical Devices", assetType: "equity", exchange: "NYSE" },
  { ticker: "RHHBY", name: "Roche Holding AG", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "OTC" },
  { ticker: "SNY", name: "Sanofi", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "GSK", name: "GSK plc", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "NVO", name: "Novo Nordisk A/S", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },
  { ticker: "AZN", name: "AstraZeneca PLC", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "equity", exchange: "NYSE" },

  // ─── FINANCIAL SERVICES ───────────────────────────────────────────────
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "BAC", name: "Bank of America Corporation", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "WFC", name: "Wells Fargo & Company", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "GS", name: "Goldman Sachs Group Inc.", sector: "Financial Services", industry: "Capital Markets", assetType: "equity", exchange: "NYSE" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financial Services", industry: "Capital Markets", assetType: "equity", exchange: "NYSE" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Financial Services", industry: "Asset Management", assetType: "equity", exchange: "NYSE" },
  { ticker: "SCHW", name: "Charles Schwab Corporation", sector: "Financial Services", industry: "Capital Markets", assetType: "equity", exchange: "NYSE" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "AXP", name: "American Express Company", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "V", name: "Visa Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "MA", name: "Mastercard Incorporated", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "PNC", name: "The PNC Financial Services Group", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "TFC", name: "Truist Financial Corporation", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "COF", name: "Capital One Financial Corporation", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "DFS", name: "Discover Financial Services", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "SYF", name: "Synchrony Financial", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Financial Services", industry: "Insurance - Life", assetType: "equity", exchange: "NYSE" },
  { ticker: "PRU", name: "Prudential Financial Inc.", sector: "Financial Services", industry: "Insurance - Life", assetType: "equity", exchange: "NYSE" },
  { ticker: "AIG", name: "American International Group Inc.", sector: "Financial Services", industry: "Insurance - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "ALL", name: "The Allstate Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NYSE" },
  { ticker: "TRV", name: "The Travelers Companies Inc.", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NYSE" },
  { ticker: "CB", name: "Chubb Limited", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NYSE" },
  { ticker: "MMC", name: "Marsh & McLennan Companies Inc.", sector: "Financial Services", industry: "Insurance Brokers", assetType: "equity", exchange: "NYSE" },
  { ticker: "AON", name: "Aon plc", sector: "Financial Services", industry: "Insurance Brokers", assetType: "equity", exchange: "NYSE" },
  { ticker: "CME", name: "CME Group Inc.", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ICE", name: "Intercontinental Exchange Inc.", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", assetType: "equity", exchange: "NYSE" },
  { ticker: "SPGI", name: "S&P Global Inc.", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", assetType: "equity", exchange: "NYSE" },
  { ticker: "MCO", name: "Moody's Corporation", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", assetType: "equity", exchange: "NYSE" },
  { ticker: "FIS", name: "Fidelity National Information Services", sector: "Financial Services", industry: "Information Technology Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "FISV", name: "Fiserv Inc.", sector: "Financial Services", industry: "Information Technology Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ADP", name: "Automatic Data Processing Inc.", sector: "Financial Services", industry: "Information Technology Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PGR", name: "The Progressive Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NYSE" },
  { ticker: "BRK-B", name: "Berkshire Hathaway Inc.", sector: "Financial Services", industry: "Insurance - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "TROW", name: "T. Rowe Price Group Inc.", sector: "Financial Services", industry: "Asset Management", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BK", name: "The Bank of New York Mellon", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "STT", name: "State Street Corporation", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "NTRS", name: "Northern Trust Corporation", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CFG", name: "Citizens Financial Group Inc.", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "FITB", name: "Fifth Third Bancorp", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "RF", name: "Regions Financial Corporation", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "KEY", name: "KeyCorp", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "HBAN", name: "Huntington Bancshares Inc.", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ZION", name: "Zions Bancorporation N.A.", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WBS", name: "Webster Financial Corporation", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NYSE" },
  { ticker: "AFL", name: "Aflac Incorporated", sector: "Financial Services", industry: "Insurance - Life", assetType: "equity", exchange: "NYSE" },
  { ticker: "CINF", name: "Cincinnati Financial Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HIG", name: "The Hartford Financial Services Group", sector: "Financial Services", industry: "Insurance - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "LNC", name: "Lincoln National Corporation", sector: "Financial Services", industry: "Insurance - Life", assetType: "equity", exchange: "NYSE" },
  { ticker: "MKTX", name: "MarketAxess Holdings Inc.", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PFG", name: "Principal Financial Group Inc.", sector: "Financial Services", industry: "Insurance - Life", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WRB", name: "W. R. Berkley Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NYSE" },
  { ticker: "ACGL", name: "Arch Capital Group Ltd.", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "RNR", name: "RenaissanceRe Holdings Ltd.", sector: "Financial Services", industry: "Insurance - Reinsurance", assetType: "equity", exchange: "NYSE" },
  { ticker: "BRO", name: "Brown & Brown Inc.", sector: "Financial Services", industry: "Insurance Brokers", assetType: "equity", exchange: "NYSE" },
  { ticker: "KNSL", name: "Kinsale Capital Group Inc.", sector: "Financial Services", industry: "Insurance - Property & Casualty", assetType: "equity", exchange: "NYSE" },
  { ticker: "COIN", name: "Coinbase Global Inc.", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HOOD", name: "Robinhood Markets Inc.", sector: "Financial Services", industry: "Capital Markets", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SOFI", name: "SoFi Technologies Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AFRM", name: "Affirm Holdings Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "UPST", name: "Upstart Holdings Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HSBC", name: "HSBC Holdings plc", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "MFG", name: "Mitsubishi UFJ Financial Group", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "DB", name: "Deutsche Bank AG", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "UBS", name: "UBS Group AG", sector: "Financial Services", industry: "Banks - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "VLY", name: "Valley National Bancorp", sector: "Financial Services", industry: "Banks - Regional", assetType: "equity", exchange: "NASDAQ" },

  // ─── CONSUMER CYCLICAL ────────────────────────────────────────────────
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HD", name: "The Home Depot Inc.", sector: "Consumer Cyclical", industry: "Home Improvement Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "MCD", name: "McDonald's Corporation", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "NKE", name: "NIKE Inc.", sector: "Consumer Cyclical", industry: "Footwear & Accessories", assetType: "equity", exchange: "NYSE" },
  { ticker: "SBUX", name: "Starbucks Corporation", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "TJX", name: "The TJX Companies Inc.", sector: "Consumer Cyclical", industry: "Apparel Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Cyclical", industry: "Home Improvement Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "BKNG", name: "Booking Holdings Inc.", sector: "Consumer Cyclical", industry: "Travel Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CMG", name: "Chipotle Mexican Grill Inc.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "ORLY", name: "O'Reilly Automotive Inc.", sector: "Consumer Cyclical", industry: "Auto Parts", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AZO", name: "AutoZone Inc.", sector: "Consumer Cyclical", industry: "Auto Parts", assetType: "equity", exchange: "NYSE" },
  { ticker: "ROST", name: "Ross Stores Inc.", sector: "Consumer Cyclical", industry: "Apparel Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MAR", name: "Marriott International Inc.", sector: "Consumer Cyclical", industry: "Lodging", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HLT", name: "Hilton Worldwide Holdings Inc.", sector: "Consumer Cyclical", industry: "Lodging", assetType: "equity", exchange: "NYSE" },
  { ticker: "YUM", name: "Yum! Brands Inc.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "GM", name: "General Motors Company", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NYSE" },
  { ticker: "F", name: "Ford Motor Company", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NYSE" },
  { ticker: "RCL", name: "Royal Caribbean Cruises Ltd.", sector: "Consumer Cyclical", industry: "Travel Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "CCL", name: "Carnival Corporation", sector: "Consumer Cyclical", industry: "Travel Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Consumer Cyclical", industry: "Travel Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "DASH", name: "DoorDash Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "UBER", name: "Uber Technologies Inc.", sector: "Consumer Cyclical", industry: "Software - Application", assetType: "equity", exchange: "NYSE" },
  { ticker: "LYFT", name: "Lyft Inc.", sector: "Consumer Cyclical", industry: "Software - Application", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "LEN", name: "Lennar Corporation", sector: "Consumer Cyclical", industry: "Residential Construction", assetType: "equity", exchange: "NYSE" },
  { ticker: "DHI", name: "D.R. Horton Inc.", sector: "Consumer Cyclical", industry: "Residential Construction", assetType: "equity", exchange: "NYSE" },
  { ticker: "TOL", name: "Toll Brothers Inc.", sector: "Consumer Cyclical", industry: "Residential Construction", assetType: "equity", exchange: "NYSE" },
  { ticker: "PHM", name: "PulteGroup Inc.", sector: "Consumer Cyclical", industry: "Residential Construction", assetType: "equity", exchange: "NYSE" },
  { ticker: "NVR", name: "NVR Inc.", sector: "Consumer Cyclical", industry: "Residential Construction", assetType: "equity", exchange: "NYSE" },
  { ticker: "DG", name: "Dollar General Corporation", sector: "Consumer Cyclical", industry: "Discount Stores", assetType: "equity", exchange: "NYSE" },
  { ticker: "DLTR", name: "Dollar Tree Inc.", sector: "Consumer Cyclical", industry: "Discount Stores", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BABA", name: "Alibaba Group Holding Limited", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "PDD", name: "PDD Holdings Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "JD", name: "JD.com Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "NIO", name: "NIO Inc.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NYSE" },
  { ticker: "SONY", name: "Sony Group Corporation", sector: "Consumer Cyclical", industry: "Consumer Electronics", assetType: "equity", exchange: "NYSE" },
  { ticker: "TM", name: "Toyota Motor Corporation", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NYSE" },
  { ticker: "APTV", name: "Aptiv PLC", sector: "Consumer Cyclical", industry: "Auto Parts", assetType: "equity", exchange: "NYSE" },
  { ticker: "ALV", name: "Autoliv Inc.", sector: "Consumer Cyclical", industry: "Auto Parts", assetType: "equity", exchange: "NYSE" },
  { ticker: "BBY", name: "Best Buy Co. Inc.", sector: "Consumer Cyclical", industry: "Electronics & Appliance Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "TPR", name: "Tapestry Inc.", sector: "Consumer Cyclical", industry: "Luxury Goods", assetType: "equity", exchange: "NYSE" },
  { ticker: "PVH", name: "PVH Corp.", sector: "Consumer Cyclical", industry: "Apparel Manufacturing", assetType: "equity", exchange: "NYSE" },
  { ticker: "RL", name: "Ralph Lauren Corporation", sector: "Consumer Cyclical", industry: "Apparel Manufacturing", assetType: "equity", exchange: "NYSE" },
  { ticker: "VFC", name: "V.F. Corporation", sector: "Consumer Cyclical", industry: "Apparel Manufacturing", assetType: "equity", exchange: "NYSE" },
  { ticker: "LULU", name: "Lululemon Athletica Inc.", sector: "Consumer Cyclical", industry: "Apparel Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ULTA", name: "Ulta Beauty Inc.", sector: "Consumer Cyclical", industry: "Specialty Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "TSCO", name: "Tractor Supply Company", sector: "Consumer Cyclical", industry: "Specialty Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "POOL", name: "Pool Corporation", sector: "Consumer Cyclical", industry: "Specialty Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CVNA", name: "Carvana Co.", sector: "Consumer Cyclical", industry: "Auto & Truck Dealerships", assetType: "equity", exchange: "NYSE" },
  { ticker: "DRI", name: "Darden Restaurants Inc.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "YUMC", name: "Yum China Holdings Inc.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "BROS", name: "Dutch Bros Inc.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "CAVA", name: "CAVA Group Inc.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NYSE" },
  { ticker: "DKNG", name: "DraftKings Inc.", sector: "Consumer Cyclical", industry: "Gambling", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PENN", name: "Penn National Gaming Inc.", sector: "Consumer Cyclical", industry: "Gambling", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MGM", name: "MGM Resorts International", sector: "Consumer Cyclical", industry: "Resorts & Casinos", assetType: "equity", exchange: "NYSE" },
  { ticker: "LVS", name: "Las Vegas Sands Corp.", sector: "Consumer Cyclical", industry: "Resorts & Casinos", assetType: "equity", exchange: "NYSE" },
  { ticker: "WYNN", name: "Wynn Resorts Limited", sector: "Consumer Cyclical", industry: "Resorts & Casinos", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CZR", name: "Caesars Entertainment Inc.", sector: "Consumer Cyclical", industry: "Resorts & Casinos", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "LCID", name: "Lucid Group Inc.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "RIVN", name: "Rivian Automotive Inc.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PTON", name: "Peloton Interactive Inc.", sector: "Consumer Cyclical", industry: "Leisure", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "ETSY", name: "Etsy Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "EBAY", name: "eBay Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "GME", name: "GameStop Corp.", sector: "Consumer Cyclical", industry: "Specialty Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "AMC", name: "AMC Entertainment Holdings Inc.", sector: "Consumer Cyclical", industry: "Movies & Entertainment", assetType: "equity", exchange: "NYSE" },
  { ticker: "CARG", name: "CarGurus Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CBRL", name: "Cracker Barrel Old Country Store", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FBHS", name: "Fortune Brands Innovations Inc.", sector: "Consumer Cyclical", industry: "Building Products & Equipment", assetType: "equity", exchange: "NYSE" },

  // ─── ENERGY ───────────────────────────────────────────────────────────
  { ticker: "XOM", name: "Exxon Mobil Corporation", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "equity", exchange: "NYSE" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "equity", exchange: "NYSE" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "EOG", name: "EOG Resources Inc.", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "MPC", name: "Marathon Petroleum Corporation", sector: "Energy", industry: "Oil & Gas Refining & Marketing", assetType: "equity", exchange: "NYSE" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", industry: "Oil & Gas Refining & Marketing", assetType: "equity", exchange: "NYSE" },
  { ticker: "VLO", name: "Valero Energy Corporation", sector: "Energy", industry: "Oil & Gas Refining & Marketing", assetType: "equity", exchange: "NYSE" },
  { ticker: "OXY", name: "Occidental Petroleum Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "HES", name: "Hess Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "DVN", name: "Devon Energy Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "SLB", name: "Schlumberger N.V.", sector: "Energy", industry: "Oil & Gas Equipment & Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "HAL", name: "Halliburton Company", sector: "Energy", industry: "Oil & Gas Equipment & Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "BKR", name: "Baker Hughes Company", sector: "Energy", industry: "Oil & Gas Equipment & Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "APA", name: "APA Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FANG", name: "Diamondback Energy Inc.", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PXD", name: "Pioneer Natural Resources Company", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "WMB", name: "The Williams Companies Inc.", sector: "Energy", industry: "Oil & Gas Midstream", assetType: "equity", exchange: "NYSE" },
  { ticker: "KMI", name: "Kinder Morgan Inc.", sector: "Energy", industry: "Oil & Gas Midstream", assetType: "equity", exchange: "NYSE" },
  { ticker: "OKE", name: "ONEOK Inc.", sector: "Energy", industry: "Oil & Gas Midstream", assetType: "equity", exchange: "NYSE" },
  { ticker: "ET", name: "Energy Transfer LP", sector: "Energy", industry: "Oil & Gas Midstream", assetType: "equity", exchange: "NYSE" },
  { ticker: "MRO", name: "Marathon Oil Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "OVV", name: "Ovintiv Inc.", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "RRC", name: "Range Resources Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "SWN", name: "Southwestern Energy Company", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "EQT", name: "EQT Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "CHRD", name: "Chord Energy Corporation", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SM", name: "SM Energy Company", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },
  { ticker: "BP", name: "BP p.l.c.", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "equity", exchange: "NYSE" },
  { ticker: "SHEL", name: "Shell plc", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "equity", exchange: "NYSE" },
  { ticker: "NOG", name: "Northern Oil and Gas Inc.", sector: "Energy", industry: "Oil & Gas E&P", assetType: "equity", exchange: "NYSE" },

  // ─── INDUSTRIALS ──────────────────────────────────────────────────────
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "HON", name: "Honeywell International Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BA", name: "The Boeing Company", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "GE", name: "General Electric Company", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "MMM", name: "3M Company", sector: "Industrials", industry: "Conglomerates", assetType: "equity", exchange: "NYSE" },
  { ticker: "UPS", name: "United Parcel Service Inc.", sector: "Industrials", industry: "Integrated Freight & Logistics", assetType: "equity", exchange: "NYSE" },
  { ticker: "FDX", name: "FedEx Corporation", sector: "Industrials", industry: "Integrated Freight & Logistics", assetType: "equity", exchange: "NYSE" },
  { ticker: "CSX", name: "CSX Corporation", sector: "Industrials", industry: "Railroads", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "NSC", name: "Norfolk Southern Corporation", sector: "Industrials", industry: "Railroads", assetType: "equity", exchange: "NYSE" },
  { ticker: "WM", name: "Waste Management Inc.", sector: "Industrials", industry: "Waste Management", assetType: "equity", exchange: "NYSE" },
  { ticker: "RSG", name: "Republic Services Inc.", sector: "Industrials", industry: "Waste Management", assetType: "equity", exchange: "NYSE" },
  { ticker: "EMR", name: "Emerson Electric Co.", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "ITW", name: "Illinois Tool Works Inc.", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "ETN", name: "Eaton Corporation plc", sector: "Industrials", industry: "Electrical Equipment & Parts", assetType: "equity", exchange: "NYSE" },
  { ticker: "GD", name: "General Dynamics Corporation", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "NOC", name: "Northrop Grumman Corporation", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "LHX", name: "L3Harris Technologies Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "PH", name: "Parker-Hannifin Corporation", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "ROK", name: "Rockwell Automation Inc.", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "OTIS", name: "Otis Worldwide Corporation", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "TT", name: "Trane Technologies plc", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "GWW", name: "W.W. Grainger Inc.", sector: "Industrials", industry: "Industrial Distribution", assetType: "equity", exchange: "NYSE" },
  { ticker: "FAST", name: "Fastenal Company", sector: "Industrials", industry: "Industrial Distribution", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "DAL", name: "Delta Air Lines Inc.", sector: "Industrials", industry: "Airlines", assetType: "equity", exchange: "NYSE" },
  { ticker: "UAL", name: "United Airlines Holdings Inc.", sector: "Industrials", industry: "Airlines", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "LUV", name: "Southwest Airlines Co.", sector: "Industrials", industry: "Airlines", assetType: "equity", exchange: "NYSE" },
  { ticker: "AAL", name: "American Airlines Group Inc.", sector: "Industrials", industry: "Airlines", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "JBLU", name: "JetBlue Airways Corporation", sector: "Industrials", industry: "Airlines", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SWK", name: "Stanley Black & Decker Inc.", sector: "Industrials", industry: "Tools & Accessories", assetType: "equity", exchange: "NYSE" },
  { ticker: "XYL", name: "Xylem Inc.", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "IR", name: "Ingersoll Rand Inc.", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "TDG", name: "TransDigm Group Incorporated", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "HII", name: "Huntington Ingalls Industries Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "TXT", name: "Textron Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "IEX", name: "IDEX Corporation", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "CMI", name: "Cummins Inc.", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "JCI", name: "Johnson Controls International plc", sector: "Industrials", industry: "Building Products & Equipment", assetType: "equity", exchange: "NYSE" },
  { ticker: "CARR", name: "Carrier Global Corporation", sector: "Industrials", industry: "Building Products & Equipment", assetType: "equity", exchange: "NYSE" },
  { ticker: "FTV", name: "Fortive Corporation", sector: "Industrials", industry: "Scientific & Technical Instruments", assetType: "equity", exchange: "NYSE" },
  { ticker: "MAS", name: "Masco Corporation", sector: "Industrials", industry: "Building Products & Equipment", assetType: "equity", exchange: "NYSE" },
  { ticker: "AOS", name: "A. O. Smith Corporation", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NYSE" },
  { ticker: "GNRC", name: "Generac Holdings Inc.", sector: "Industrials", industry: "Electrical Equipment & Parts", assetType: "equity", exchange: "NYSE" },
  { ticker: "NDSN", name: "Nordson Corporation", sector: "Industrials", industry: "Industrial Machinery", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WTW", name: "Willis Towers Watson plc", sector: "Industrials", industry: "Insurance Brokers", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CPRT", name: "Copart Inc.", sector: "Industrials", industry: "Business Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "MAN", name: "ManpowerGroup Inc.", sector: "Industrials", industry: "Staffing & Employment Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "SNA", name: "Snap-on Incorporated", sector: "Industrials", industry: "Tools & Accessories", assetType: "equity", exchange: "NYSE" },
  { ticker: "J", name: "Jacobs Solutions Inc.", sector: "Industrials", industry: "Engineering & Construction", assetType: "equity", exchange: "NYSE" },
  { ticker: "RXO", name: "RXO Inc.", sector: "Industrials", industry: "Integrated Freight & Logistics", assetType: "equity", exchange: "NYSE" },
  { ticker: "ACHR", name: "Archer Aviation Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "JOBY", name: "Joby Aviation Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NYSE" },
  { ticker: "RKLB", name: "Rocket Lab USA Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "AGCO", name: "AGCO Corporation", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "equity", exchange: "NYSE" },

  // ─── COMMUNICATION SERVICES ───────────────────────────────────────────
  { ticker: "DIS", name: "The Walt Disney Company", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NYSE" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CMCSA", name: "Comcast Corporation", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication Services", industry: "Telecom Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "VZ", name: "Verizon Communications Inc.", sector: "Communication Services", industry: "Telecom Services", assetType: "equity", exchange: "NYSE" },
  { ticker: "TMUS", name: "T-Mobile US Inc.", sector: "Communication Services", industry: "Telecom Services", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CHTR", name: "Charter Communications Inc.", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "EA", name: "Electronic Arts Inc.", sector: "Communication Services", industry: "Electronic Gaming & Multimedia", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "TTWO", name: "Take-Two Interactive Software Inc.", sector: "Communication Services", industry: "Electronic Gaming & Multimedia", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WBD", name: "Warner Bros. Discovery Inc.", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PARA", name: "Paramount Global", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "FOXA", name: "Fox Corporation", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "OMC", name: "Omnicom Group Inc.", sector: "Communication Services", industry: "Advertising Agencies", assetType: "equity", exchange: "NYSE" },
  { ticker: "WPP", name: "WPP plc", sector: "Communication Services", industry: "Advertising Agencies", assetType: "equity", exchange: "NYSE" },
  { ticker: "IPG", name: "The Interpublic Group of Companies", sector: "Communication Services", industry: "Advertising Agencies", assetType: "equity", exchange: "NYSE" },
  { ticker: "MTCH", name: "Match Group Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BIDU", name: "Baidu Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "SNAP", name: "Snap Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "equity", exchange: "NYSE" },
  { ticker: "PINS", name: "Pinterest Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "equity", exchange: "NYSE" },
  { ticker: "SPOT", name: "Spotify Technology S.A.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "equity", exchange: "NYSE" },
  { ticker: "LYV", name: "Live Nation Entertainment Inc.", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NYSE" },
  { ticker: "TCEHY", name: "Tencent Holdings Limited", sector: "Communication Services", industry: "Internet Content & Information", assetType: "equity", exchange: "OTC" },
  { ticker: "RBLX", name: "Roblox Corporation", sector: "Communication Services", industry: "Electronic Gaming & Multimedia", assetType: "equity", exchange: "NYSE" },
  { ticker: "DISH", name: "Dish Network Corporation", sector: "Communication Services", industry: "Entertainment", assetType: "equity", exchange: "NASDAQ" },

  // ─── REAL ESTATE ──────────────────────────────────────────────────────
  { ticker: "AMT", name: "American Tower Corporation", sector: "Real Estate", industry: "REIT - Specialty", assetType: "equity", exchange: "NYSE" },
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate", industry: "REIT - Industrial", assetType: "equity", exchange: "NYSE" },
  { ticker: "CCI", name: "Crown Castle Inc.", sector: "Real Estate", industry: "REIT - Specialty", assetType: "equity", exchange: "NYSE" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate", industry: "REIT - Specialty", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate", industry: "REIT - Self-Storage", assetType: "equity", exchange: "NYSE" },
  { ticker: "O", name: "Realty Income Corporation", sector: "Real Estate", industry: "REIT - Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "WELL", name: "Welltower Inc.", sector: "Real Estate", industry: "REIT - Healthcare Facilities", assetType: "equity", exchange: "NYSE" },
  { ticker: "SPG", name: "Simon Property Group Inc.", sector: "Real Estate", industry: "REIT - Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "DLR", name: "Digital Realty Trust Inc.", sector: "Real Estate", industry: "REIT - Specialty", assetType: "equity", exchange: "NYSE" },
  { ticker: "AVB", name: "AvalonBay Communities Inc.", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "WY", name: "Weyerhaeuser Company", sector: "Real Estate", industry: "REIT - Specialty", assetType: "equity", exchange: "NYSE" },
  { ticker: "ARE", name: "Alexandria Real Estate Equities Inc.", sector: "Real Estate", industry: "REIT - Office", assetType: "equity", exchange: "NYSE" },
  { ticker: "VICI", name: "VICI Properties Inc.", sector: "Real Estate", industry: "REIT - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "OHI", name: "Omega Healthcare Investors Inc.", sector: "Real Estate", industry: "REIT - Healthcare Facilities", assetType: "equity", exchange: "NYSE" },
  { ticker: "WPC", name: "W. P. Carey Inc.", sector: "Real Estate", industry: "REIT - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "INVH", name: "Invitation Homes Inc.", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "MAA", name: "Mid-America Apartment Communities Inc.", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "ESS", name: "Essex Property Trust Inc.", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "VTR", name: "Ventas Inc.", sector: "Real Estate", industry: "REIT - Healthcare Facilities", assetType: "equity", exchange: "NYSE" },
  { ticker: "BXP", name: "Boston Properties Inc.", sector: "Real Estate", industry: "REIT - Office", assetType: "equity", exchange: "NYSE" },
  { ticker: "KIM", name: "Kimco Realty Corporation", sector: "Real Estate", industry: "REIT - Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "REG", name: "Regency Centers Corporation", sector: "Real Estate", industry: "REIT - Retail", assetType: "equity", exchange: "NYSE" },
  { ticker: "VNO", name: "Vornado Realty Trust", sector: "Real Estate", industry: "REIT - Office", assetType: "equity", exchange: "NYSE" },
  { ticker: "UDR", name: "UDR Inc.", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "CPT", name: "Camden Property Trust", sector: "Real Estate", industry: "REIT - Residential", assetType: "equity", exchange: "NYSE" },
  { ticker: "EXR", name: "Extra Space Storage Inc.", sector: "Real Estate", industry: "REIT - Self-Storage", assetType: "equity", exchange: "NYSE" },
  { ticker: "STAG", name: "STAG Industrial Inc.", sector: "Real Estate", industry: "REIT - Industrial", assetType: "equity", exchange: "NYSE" },
  { ticker: "EPR", name: "EPR Properties", sector: "Real Estate", industry: "REIT - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "IIPR", name: "Innovative Industrial Properties Inc.", sector: "Real Estate", industry: "REIT - Specialty", assetType: "equity", exchange: "NYSE" },

  // ─── UTILITIES ────────────────────────────────────────────────────────
  { ticker: "NEE", name: "NextEra Energy Inc.", sector: "Utilities", industry: "Utilities - Renewable", assetType: "equity", exchange: "NYSE" },
  { ticker: "DUK", name: "Duke Energy Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "SO", name: "The Southern Company", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "D", name: "Dominion Energy Inc.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "AEP", name: "American Electric Power Co. Inc.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "XEL", name: "Xcel Energy Inc.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WEC", name: "WEC Energy Group Inc.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "ED", name: "Consolidated Edison Inc.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "AWK", name: "American Water Works Company Inc.", sector: "Utilities", industry: "Utilities - Regulated Water", assetType: "equity", exchange: "NYSE" },
  { ticker: "SRE", name: "Sempra", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "DTE", name: "DTE Energy Company", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "ETR", name: "Entergy Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "CEG", name: "Constellation Energy Corporation", sector: "Utilities", industry: "Utilities - Diversified", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PCG", name: "PG&E Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "FE", name: "FirstEnergy Corp.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "PPL", name: "PPL Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "CMS", name: "CMS Energy Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "AES", name: "The AES Corporation", sector: "Utilities", industry: "Utilities - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "PEG", name: "Public Service Enterprise Group", sector: "Utilities", industry: "Utilities - Diversified", assetType: "equity", exchange: "NYSE" },
  { ticker: "NRG", name: "NRG Energy Inc.", sector: "Utilities", industry: "Utilities - Independent Power Producers", assetType: "equity", exchange: "NYSE" },
  { ticker: "PNW", name: "Pinnacle West Capital Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "OGE", name: "OGE Energy Corp.", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },
  { ticker: "ATO", name: "Atmos Energy Corporation", sector: "Utilities", industry: "Utilities - Regulated Gas", assetType: "equity", exchange: "NYSE" },
  { ticker: "EXC", name: "Exelon Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "LNT", name: "Alliant Energy Corporation", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BEP", name: "Brookfield Renewable Partners L.P.", sector: "Utilities", industry: "Utilities - Renewable", assetType: "equity", exchange: "NYSE" },
  { ticker: "EIX", name: "Edison International", sector: "Utilities", industry: "Utilities - Regulated Electric", assetType: "equity", exchange: "NYSE" },

  // ─── MATERIALS ────────────────────────────────────────────────────────
  { ticker: "LIN", name: "Linde plc", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "APD", name: "Air Products and Chemicals Inc.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "SHW", name: "The Sherwin-Williams Company", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "ECL", name: "Ecolab Inc.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "DD", name: "DuPont de Nemours Inc.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "NEM", name: "Newmont Corporation", sector: "Materials", industry: "Gold", assetType: "equity", exchange: "NYSE" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", sector: "Materials", industry: "Copper", assetType: "equity", exchange: "NYSE" },
  { ticker: "NUE", name: "Nucor Corporation", sector: "Materials", industry: "Steel", assetType: "equity", exchange: "NYSE" },
  { ticker: "STLD", name: "Steel Dynamics Inc.", sector: "Materials", industry: "Steel", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CF", name: "CF Industries Holdings Inc.", sector: "Materials", industry: "Agricultural Inputs", assetType: "equity", exchange: "NYSE" },
  { ticker: "MOS", name: "The Mosaic Company", sector: "Materials", industry: "Agricultural Inputs", assetType: "equity", exchange: "NYSE" },
  { ticker: "LYB", name: "LyondellBasell Industries N.V.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "EMN", name: "Eastman Chemical Company", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "PPG", name: "PPG Industries Inc.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "VMC", name: "Vulcan Materials Company", sector: "Materials", industry: "Building Materials", assetType: "equity", exchange: "NYSE" },
  { ticker: "MLM", name: "Martin Marietta Materials Inc.", sector: "Materials", industry: "Building Materials", assetType: "equity", exchange: "NYSE" },
  { ticker: "CE", name: "Celanese Corporation", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "ALB", name: "Albemarle Corporation", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "IFF", name: "International Flavors & Fragrances Inc.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "DOW", name: "Dow Inc.", sector: "Materials", industry: "Specialty Chemicals", assetType: "equity", exchange: "NYSE" },
  { ticker: "BHP", name: "BHP Group Limited", sector: "Materials", industry: "Other Industrial Metals & Mining", assetType: "equity", exchange: "NYSE" },
  { ticker: "AEM", name: "Agnico Eagle Mines Limited", sector: "Materials", industry: "Gold", assetType: "equity", exchange: "NYSE" },
  { ticker: "PKX", name: "POSCO Holdings Inc.", sector: "Materials", industry: "Steel", assetType: "equity", exchange: "NYSE" },
  { ticker: "CRS", name: "Carpenter Technology Corporation", sector: "Materials", industry: "Steel", assetType: "equity", exchange: "NYSE" },
  { ticker: "AMCR", name: "Amcor plc", sector: "Materials", industry: "Packaging & Containers", assetType: "equity", exchange: "NYSE" },
  { ticker: "WRK", name: "WestRock Company", sector: "Materials", industry: "Packaging & Containers", assetType: "equity", exchange: "NYSE" },
  { ticker: "GLNCY", name: "Glencore plc", sector: "Materials", industry: "Other Industrial Metals & Mining", assetType: "equity", exchange: "OTC" },

  // ─── CONSUMER DEFENSIVE ───────────────────────────────────────────────
  { ticker: "PG", name: "The Procter & Gamble Company", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "KO", name: "The Coca-Cola Company", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "equity", exchange: "NYSE" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "equity", exchange: "NYSE" },
  { ticker: "COST", name: "Costco Wholesale Corporation", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "PM", name: "Philip Morris International Inc.", sector: "Consumer Defensive", industry: "Tobacco", assetType: "equity", exchange: "NYSE" },
  { ticker: "MO", name: "Altria Group Inc.", sector: "Consumer Defensive", industry: "Tobacco", assetType: "equity", exchange: "NYSE" },
  { ticker: "CL", name: "Colgate-Palmolive Company", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "KMB", name: "Kimberly-Clark Corporation", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "GIS", name: "General Mills Inc.", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "KHC", name: "The Kraft Heinz Company", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "HSY", name: "The Hershey Company", sector: "Consumer Defensive", industry: "Confectioners", assetType: "equity", exchange: "NYSE" },
  { ticker: "STZ", name: "Constellation Brands Inc.", sector: "Consumer Defensive", industry: "Beverages - Wineries & Distilleries", assetType: "equity", exchange: "NYSE" },
  { ticker: "MNST", name: "Monster Beverage Corporation", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "KDP", name: "Keurig Dr Pepper Inc.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "K", name: "Kellogg Company", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "CPB", name: "The Campbell's Company", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "SYY", name: "Sysco Corporation", sector: "Consumer Defensive", industry: "Food Distribution", assetType: "equity", exchange: "NYSE" },
  { ticker: "TSN", name: "Tyson Foods Inc.", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "MDLZ", name: "Mondelez International Inc.", sector: "Consumer Defensive", industry: "Confectioners", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "CAG", name: "Conagra Brands Inc.", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "SJM", name: "The J.M. Smucker Company", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "CLX", name: "The Clorox Company", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "CHD", name: "Church & Dwight Co. Inc.", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "EL", name: "The Estée Lauder Companies Inc.", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "equity", exchange: "NYSE" },
  { ticker: "KR", name: "The Kroger Co.", sector: "Consumer Defensive", industry: "Grocery Stores", assetType: "equity", exchange: "NYSE" },
  { ticker: "MKC", name: "McCormick & Company Incorporated", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "HRL", name: "Hormel Foods Corporation", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "NWL", name: "Newell Brands Inc.", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BTI", name: "British American Tobacco p.l.c.", sector: "Consumer Defensive", industry: "Tobacco", assetType: "equity", exchange: "NYSE" },
  { ticker: "UL", name: "Unilever plc", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "equity", exchange: "NYSE" },
  { ticker: "LW", name: "Lamb Weston Holdings Inc.", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NYSE" },
  { ticker: "CELH", name: "Celsius Holdings Inc.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "equity", exchange: "NASDAQ" },
  { ticker: "BYND", name: "Beyond Meat Inc.", sector: "Consumer Defensive", industry: "Packaged Foods", assetType: "equity", exchange: "NASDAQ" },

  // ─── MAJOR ETFs ───────────────────────────────────────────────────────
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", sector: "ETF", industry: "Large Growth", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", sector: "ETF", industry: "Small Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "SCHD", name: "Schwab U.S. Dividend Equity ETF", sector: "ETF", industry: "Large Value", assetType: "etf", exchange: "NYSE" },
  { ticker: "VUG", name: "Vanguard Growth ETF", sector: "ETF", industry: "Large Growth", assetType: "etf", exchange: "NYSE" },
  { ticker: "VTV", name: "Vanguard Value ETF", sector: "ETF", industry: "Large Value", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", sector: "ETF", industry: "Technology", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", sector: "ETF", industry: "Financial", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund", sector: "ETF", industry: "Healthcare", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", sector: "ETF", industry: "Energy", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR Fund", sector: "ETF", industry: "Industrial", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR Fund", sector: "ETF", industry: "Consumer Defensive", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR Fund", sector: "ETF", industry: "Utilities", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLC", name: "Communication Services Select Sector SPDR Fund", sector: "ETF", industry: "Communication", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR Fund", sector: "ETF", industry: "Real Estate", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLB", name: "Materials Select Sector SPDR Fund", sector: "ETF", industry: "Materials", assetType: "etf", exchange: "NYSE" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", sector: "ETF", industry: "Consumer Cyclical", assetType: "etf", exchange: "NYSE" },
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "ETF", industry: "Innovation", assetType: "etf", exchange: "NYSE" },
  { ticker: "ARKQ", name: "ARK Autonomous Technology & Robotics ETF", sector: "ETF", industry: "Automation & Robotics", assetType: "etf", exchange: "NYSE" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF", sector: "ETF", industry: "Semiconductors", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF", sector: "ETF", industry: "Semiconductors", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "HACK", name: "First Trust NASDAQ Cybersecurity ETF", sector: "ETF", industry: "Cybersecurity", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "IBB", name: "iShares Biotechnology ETF", sector: "ETF", industry: "Biotechnology", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "XBI", name: "SPDR S&P Biotech ETF", sector: "ETF", industry: "Biotechnology", assetType: "etf", exchange: "NYSE" },
  { ticker: "GLD", name: "SPDR Gold Shares", sector: "ETF", industry: "Gold", assetType: "etf", exchange: "NYSE" },
  { ticker: "SLV", name: "iShares Silver Trust", sector: "ETF", industry: "Silver", assetType: "etf", exchange: "NYSE" },
  { ticker: "USO", name: "United States Oil Fund LP", sector: "ETF", industry: "Oil", assetType: "etf", exchange: "NYSE" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", sector: "ETF", industry: "Long-Term Treasury", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", sector: "ETF", industry: "Intermediate-Term Treasury", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", sector: "ETF", industry: "Short-Term Treasury", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "HYG", name: "iShares iBoxx $ High Yield Corporate Bond ETF", sector: "ETF", industry: "High Yield Bond", assetType: "etf", exchange: "NYSE" },
  { ticker: "LQD", name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", sector: "ETF", industry: "Investment Grade Bond", assetType: "etf", exchange: "NYSE" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", sector: "ETF", industry: "Total Bond Market", assetType: "etf", exchange: "NYSE" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", sector: "ETF", industry: "Total Bond Market", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "VNM", name: "VanEck Vietnam ETF", sector: "ETF", industry: "Vietnam", assetType: "etf", exchange: "NYSE" },
  { ticker: "KWEB", name: "KraneShares CSI China Internet ETF", sector: "ETF", industry: "China Internet", assetType: "etf", exchange: "NYSE" },
  { ticker: "FXI", name: "iShares China Large-Cap ETF", sector: "ETF", industry: "China Large-Cap", assetType: "etf", exchange: "NYSE" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", sector: "ETF", industry: "Emerging Markets", assetType: "etf", exchange: "NYSE" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF", sector: "ETF", industry: "Developed Markets", assetType: "etf", exchange: "NYSE" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", sector: "ETF", industry: "Emerging Markets", assetType: "etf", exchange: "NYSE" },
  { ticker: "TQQQ", name: "ProShares UltraPro QQQ", sector: "ETF", industry: "Leveraged Large Growth", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "SQQQ", name: "ProShares UltraPro Short QQQ", sector: "ETF", industry: "Inverse Large Growth", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "SPXU", name: "ProShares UltraPro Short S&P500", sector: "ETF", industry: "Inverse Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "UPRO", name: "ProShares UltraPro S&P500", sector: "ETF", industry: "Leveraged Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF Trust", sector: "ETF", industry: "Large Value", assetType: "etf", exchange: "NYSE" },
  { ticker: "MDY", name: "SPDR S&P MidCap 400 ETF Trust", sector: "ETF", industry: "Mid-Cap Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VO", name: "Vanguard Mid-Cap ETF", sector: "ETF", industry: "Mid-Cap Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VB", name: "Vanguard Small-Cap ETF", sector: "ETF", industry: "Small Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VGT", name: "Vanguard Information Technology ETF", sector: "ETF", industry: "Technology", assetType: "etf", exchange: "NYSE" },
  { ticker: "VHT", name: "Vanguard Health Care ETF", sector: "ETF", industry: "Healthcare", assetType: "etf", exchange: "NYSE" },
  { ticker: "VDE", name: "Vanguard Energy ETF", sector: "ETF", industry: "Energy", assetType: "etf", exchange: "NYSE" },
  { ticker: "VIS", name: "Vanguard Industrials ETF", sector: "ETF", industry: "Industrial", assetType: "etf", exchange: "NYSE" },
  { ticker: "VDC", name: "Vanguard Consumer Staples ETF", sector: "ETF", industry: "Consumer Defensive", assetType: "etf", exchange: "NYSE" },
  { ticker: "VFH", name: "Vanguard Financials ETF", sector: "ETF", industry: "Financial", assetType: "etf", exchange: "NYSE" },
  { ticker: "VCR", name: "Vanguard Consumer Discretionary ETF", sector: "ETF", industry: "Consumer Cyclical", assetType: "etf", exchange: "NYSE" },
  { ticker: "VPU", name: "Vanguard Utilities ETF", sector: "ETF", industry: "Utilities", assetType: "etf", exchange: "NYSE" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", sector: "ETF", industry: "Real Estate", assetType: "etf", exchange: "NYSE" },
  { ticker: "VT", name: "Vanguard Total World Stock ETF", sector: "ETF", industry: "World Stock", assetType: "etf", exchange: "NYSE" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", sector: "ETF", industry: "Developed Markets", assetType: "etf", exchange: "NYSE" },
  { ticker: "VGK", name: "Vanguard FTSE Europe ETF", sector: "ETF", industry: "Europe", assetType: "etf", exchange: "NYSE" },
  { ticker: "VPL", name: "Vanguard FTSE Pacific ETF", sector: "ETF", industry: "Pacific", assetType: "etf", exchange: "NYSE" },
  { ticker: "BNDX", name: "Vanguard Total International Bond ETF", sector: "ETF", industry: "Total International Bond", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "DGRW", name: "WisdomTree U.S. Quality Dividend Growth Fund", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "DGRO", name: "iShares Core Dividend Growth ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF", sector: "ETF", industry: "Large Value", assetType: "etf", exchange: "NYSE" },
  { ticker: "HDV", name: "iShares Core High Dividend ETF", sector: "ETF", industry: "Large Value", assetType: "etf", exchange: "NYSE" },
  { ticker: "NOBL", name: "ProShares S&P 500 Dividend Aristocrats ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "ICLN", name: "iShares Global Clean Energy ETF", sector: "ETF", industry: "Clean Energy", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "TAN", name: "Invesco Solar ETF", sector: "ETF", industry: "Solar", assetType: "etf", exchange: "NYSE" },
  { ticker: "LIT", name: "Global X Lithium & Battery Tech ETF", sector: "ETF", industry: "Lithium", assetType: "etf", exchange: "NYSE" },
  { ticker: "SKYY", name: "First Trust Cloud Computing ETF", sector: "ETF", industry: "Cloud Computing", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "CLOU", name: "Global X Cloud Computing ETF", sector: "ETF", industry: "Cloud Computing", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "AIQ", name: "Global X Artificial Intelligence & Technology ETF", sector: "ETF", industry: "Artificial Intelligence", assetType: "etf", exchange: "NASDAQ" },
  { ticker: "ROBO", name: "ROBO Global Robotics & Automation Index ETF", sector: "ETF", industry: "Robotics", assetType: "etf", exchange: "NYSE" },
  { ticker: "MGK", name: "Vanguard Mega Cap Growth ETF", sector: "ETF", industry: "Large Growth", assetType: "etf", exchange: "NYSE" },
  { ticker: "MGV", name: "Vanguard Mega Cap Value ETF", sector: "ETF", industry: "Large Value", assetType: "etf", exchange: "NYSE" },
  { ticker: "ESGV", name: "Vanguard ESG U.S. Stock ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
  { ticker: "VSGX", name: "Vanguard ESG International Stock ETF", sector: "ETF", industry: "International Stock", assetType: "etf", exchange: "NYSE" },
  { ticker: "SUSA", name: "iShares MSCI USA ESG Select ETF", sector: "ETF", industry: "Large Blend", assetType: "etf", exchange: "NYSE" },
];

export const SP500_TICKERS: string[] = [
  "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "BRK-B", "UNH",
  "JNJ", "XOM", "JPM", "V", "PG", "MA", "HD", "CVX", "LLY", "ABBV", "MRK",
  "AVGO", "PEP", "KO", "COST", "TMO", "MCD", "WMT", "CSCO", "ACN", "ABT",
  "DHR", "NEE", "LIN", "TXN", "PM", "RTX", "LOW", "HON", "UPS", "AMGN",
  "IBM", "QCOM", "GE", "CAT", "SPGI", "INTC", "IBM", "BA", "BLK", "SCHW",
  "NOW", "SYK", "ADP", "VRTX", "GILD", "BKNG", "MDT", "LMT", "ISRG", "SYY",
  "CB", "PLD", "CI", "MMC", "REGN", "SLB", "CL", "SNA", "SO", "EOG",
  "DUK", "PNC", "ADBE", "SNOW", "MCK", "CMG", "AON", "NOC", "TFC", "ZTS",
  "ICE", "ADI", "FIS", "WELL", "TGT", "MCO", "USB", "CSX", "FDX", "WM",
  "RSG", "AEP", "PSA", "ETN", "GD", "D", "BMY", "ELV", "ORLY", "DE",
  "LHX", "CME", "PGR", "PH", "GWW", "EMR", "ITW", "ROK", "ADSK", "NSC",
  "PCAR", "IDXX", "AFL", "STZ", "XEL", "VFC", "COF", "MPC", "DHI", "LEN",
  "FTNT", "HWM", "ODFL", "ANET", "SIVB", "TT", "KLAC", "SMCI", "LRCX",
  "SNA", "WEC", "EXC", "VLO", "OXY", "BKR", "FANG", "WMB", "KMI", "DVN",
  "ES", "AWK", "OKE", "SRE", "PSX", "ED", "ETR", "CMS", "WST", "STLD",
  "PPG", "ECL", "SHW", "NUE", "FCX", "NEM", "VMC", "MLM", "DOW", "DD",
  "APD", "EMN", "LYB", "CF", "MOS", "IFF", "CE", "ALB", "PPG", "STLD",
  "MCHP", "ANSS", "TYL", "KEYS", "PTC", "VRSN", "ZBRA", "ON", "MRVL",
  "NXPI", "QRVO", "WOLF", "CIEN", "SNPS", "CDNS", "HUBS", "TTD", "APP",
  "DDOG", "MDB", "PANW", "FTNT", "CRWD", "ZS", "NET", "PLTR", "MSTR",
  "VEEV", "FIVN", "PCTY", "SMAR", "CFLT", "IOT", "TOST", "MNDY", "WIX",
  "FVRR", "TWLO", "PSTG", "OKTA", "VRNS", "PATH", "U", "ZM", "ENPH",
  "AI", "ARM", "IONQ", "RGTI", "ASTS", "BB", "SAP", "SHOP", "SQ", "PYPL",
  "COIN", "HOOD", "SOFI", "RBLX", "DKNG", "CVNA", "LCID", "RIVN", "AFRM",
  "UPST", "CAVA", "BROS", "PTON", "ETSY", "EBAY", "GME", "AMC",
  "LULU", "ULTA", "TSCO", "POOL", "BBY", "CMG", "YUM", "MCD", "SBUX",
  "NKE", "TJX", "ROST", "MAR", "HLT", "RCL", "CCL", "ABNB", "DASH",
  "UBER", "LYFT", "GM", "F", "TSLA", "SONY", "TM", "APTV", "ALV",
  "HCA", "BSX", "RMD", "DXCM", "PODD", "STE", "UHS", "CNC", "MOH",
  "ILMN", "BMRN", "ALNY", "CRSP", "HALO", "RPRX", "DOCS", "TFX",
  "A", "WAT", "MTD", "BIO", "HOLX", "ALGN", "BAX", "INCY",
  "CAH", "HSIC", "WBA", "XRAY", "ZBH", "ELAN", "PRGO",
  "NVO", "AZN", "RHHBY", "SNY", "GSK", "TSM", "ASML",
  "HSBC", "BABA", "PDD", "JD", "NIO", "TCEHY", "BP", "SHEL",
  "GLNCY", "BHP", "AEM", "PKX", "MFG", "DB", "UBS", "UL", "BTI",
  "EIX", "AES", "NRG", "PEG", "PNW", "OGE", "ATO", "LNT", "BEP",
  "WY", "AMT", "CCI", "EQIX", "O", "SPG", "DLR", "AVB", "EQR",
  "VICI", "OHI", "WPC", "INVH", "MAA", "ESS", "VTR", "BXP",
  "KIM", "REG", "VNO", "UDR", "CPT", "EXR", "STAG", "EPR", "IIPR",
  "ARE",
];

export const ETF_TICKERS: string[] = [
  "SPY", "QQQ", "IWM", "VTI", "VOO", "IVV", "SCHD", "VUG", "VTV",
  "XLK", "XLF", "XLV", "XLE", "XLI", "XLP", "XLU", "XLC", "XLRE", "XLB", "XLY",
  "ARKK", "ARKQ", "SOXX", "SMH", "HACK", "IBB", "XBI",
  "GLD", "SLV", "USO",
  "TLT", "IEF", "SHY", "HYG", "LQD", "AGG", "BND", "BNDX",
  "VNM", "KWEB", "FXI", "EEM", "EFA", "VWO",
  "TQQQ", "SQQQ", "SPXU", "UPRO",
  "DIA", "MDY", "VO", "VB",
  "VGT", "VHT", "VDE", "VIS", "VDC", "VFH", "VCR", "VPU", "VNQ",
  "VT", "VEA", "VGK", "VPL",
  "DGRW", "DGRO", "VYM", "HDV", "NOBL",
  "ICLN", "TAN", "LIT",
  "SKYY", "CLOU", "AIQ", "ROBO",
  "MGK", "MGV", "ESGV", "VSGX", "SUSA",
];

export const INTERNATIONAL_TICKERS: string[] = [
  "TSM", "ASML", "NVO", "AZN", "HSBC", "BABA", "PDD", "BIDU", "NIO", "JD",
  "TCEHY", "SONY", "TM", "MFG", "DB", "UBS", "BP", "SHEL", "GLNCY", "BHP",
  "UL", "BTI", "RHHBY", "SNY", "GSK", "INFY", "WIT", "ERIC", "NOK",
  "NSANY", "CMWAY", "NGLOY", "VNET",
];
